# Configuration Semgrep pour le projet ATMR
# Documentation: https://semgrep.dev/docs/configuration-files/

# Règles OWASP et sécurité
rules:
  # Règles de sécurité générales
  - p/ci
  - p/security-audit

# Exclusions pour faux positifs justifiés
exclude:
  # Ignorer les fichiers de test (optionnel, décommenter si nécessaire)
  # - "**/tests/**"
  # - "**/test_*.py"
  
  # Ignorer les migrations de base de données (si applicable)
  # - "**/migrations/**"

# Exclusions spécifiques par règle
# Note: Les exclusions sont gérées via # nosemgrep inline dans le code
# pour plus de précision et de traçabilité

