apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ws-service-hpa
  namespace: atmr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ws-service
  minReplicas: 5
  maxReplicas: 36
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: websocket_connections
        target:
          type: AverageValue
          averageValue: "4000"
