name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**/*.py'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: atmr_test
          POSTGRES_USER: atmr
          POSTGRES_PASSWORD: atmr_test_password
          TZ: Europe/Zurich
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-mock responses faker
      
      - name: Run migrations
        env:
          DATABASE_URL: postgresql://atmr:atmr_test_password@localhost:5432/atmr_test
          FLASK_CONFIG: testing
          SECRET_KEY: test-secret-key-github-actions
          JWT_SECRET_KEY: test-jwt-secret-key
          APP_ENCRYPTION_KEY_B64: dGVzdF9lbmNyeXB0aW9uX2tleV8zMmJ5dGVz  # 32 bytes base64
        run: |
          cd backend
          flask db upgrade
      
      - name: Run pytest
        env:
          DATABASE_URL: postgresql://atmr:atmr_test_password@localhost:5432/atmr_test
          REDIS_URL: redis://localhost:6379/0
          FLASK_CONFIG: testing
          SECRET_KEY: test-secret-key-github-actions
          JWT_SECRET_KEY: test-jwt-secret-key
          APP_ENCRYPTION_KEY_B64: dGVzdF9lbmNyeXB0aW9uX2tleV8zMmJ5dGVz
        run: |
          cd backend
          pytest --cov=. --cov-report=xml --cov-report=html --cov-report=term -v
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true
      
      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/htmlcov/

