"""add_invoice_management_tables

Revision ID: 02e0994e702b
Revises: 6af879898b0f
Create Date: 2025-10-08 22:17:26.236130

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "02e0994e702b"
down_revision = "6af879898b0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Modifier le type invoice_status existant pour ajouter les nouvelles valeurs
    op.execute("ALTER TYPE invoice_status ADD VALUE IF NOT EXISTS 'DRAFT'")
    op.execute("ALTER TYPE invoice_status ADD VALUE IF NOT EXISTS 'SENT'")
    op.execute("ALTER TYPE invoice_status ADD VALUE IF NOT EXISTS 'PARTIALLY_PAID'")
    op.execute("ALTER TYPE invoice_status ADD VALUE IF NOT EXISTS 'OVERDUE'")
    op.execute("ALTER TYPE invoice_status ADD VALUE IF NOT EXISTS 'CANCELLED'")

    # Créer les nouveaux types d'enum s'ils n'existent pas
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE invoice_line_type AS ENUM ('RIDE', 'LATE_FEE', 'REMINDER_FEE', 'CUSTOM');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE payment_method AS ENUM ('BANK_TRANSFER', 'CASH', 'CARD', 'ADJUSTMENT');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    op.create_table(
        "company_billing_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("overdue_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reminder1_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reminder2_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reminder3_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reminder_schedule_days", sa.JSON(), nullable=False),
        sa.Column("auto_reminders_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_sender", sa.String(length=200), nullable=True),
        sa.Column("invoice_number_format", sa.String(length=50), nullable=False),
        sa.Column("invoice_prefix", sa.String(length=10), nullable=False),
        sa.Column("iban", sa.String(length=50), nullable=True),
        sa.Column("qr_iban", sa.String(length=50), nullable=True),
        sa.Column("esr_ref_base", sa.String(length=50), nullable=True),
        sa.Column("invoice_message_template", sa.Text(), nullable=True),
        sa.Column("reminder1_template", sa.Text(), nullable=True),
        sa.Column("reminder2_template", sa.Text(), nullable=True),
        sa.Column("reminder3_template", sa.Text(), nullable=True),
        sa.Column("legal_footer", sa.Text(), nullable=True),
        sa.Column("pdf_template_variant", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id"),
    )
    op.create_table(
        "invoice_sequences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "year", "month", name="uq_company_year_month"
        ),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("late_fee_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "reminder_fee_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("balance_due", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT",
                "SENT",
                "PARTIALLY_PAID",
                "PAID",
                "OVERDUE",
                "CANCELLED",
                name="invoice_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reminder_level", sa.Integer(), nullable=False),
        sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("qr_reference", sa.String(length=50), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("total_amount >= 0", name="chk_invoice_amount_positive"),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"]),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "invoice_number", name="uq_company_invoice_number"
        ),
    )
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_invoice_company_period",
            ["company_id", "period_year", "period_month"],
            unique=False,
        )
        batch_op.create_index("ix_invoice_due_date", ["due_date"], unique=False)
        batch_op.create_index(
            "ix_invoice_status", ["company_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invoices_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invoices_company_id"), ["company_id"], unique=False
        )

    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "RIDE",
                "LATE_FEE",
                "REMINDER_FEE",
                "CUSTOM",
                name="invoice_line_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("qty", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"]),
        sa.ForeignKeyConstraint(["reservation_id"], ["booking.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoice_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "method",
            postgresql.ENUM(
                "BANK_TRANSFER",
                "CASH",
                "CARD",
                "ADJUSTMENT",
                name="payment_method",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoice_reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("added_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.drop_index("ix_invoice_booking_id")
        batch_op.drop_index("ix_invoice_company_id")
        batch_op.drop_index("ix_invoice_company_status_due")
        batch_op.drop_index("ix_invoice_reference")
        batch_op.drop_index("ix_invoice_user_created")
        batch_op.drop_index("ix_invoice_user_id")

    op.drop_table("invoice")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Supprimer les types d'enum créés
    op.execute("DROP TYPE IF EXISTS payment_method")
    op.execute("DROP TYPE IF EXISTS invoice_line_type")

    op.create_table(
        "invoice",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "reference", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("booking_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "pdf_url", sa.VARCHAR(length=0.255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "due_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "paid_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("UNPAID", "PAID", "CANCELED", name="invoice_status"),
            server_default=sa.text("'UNPAID'::invoice_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0::double precision", name="chk_invoice_amount_positive"
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
            name="fk_invoice_booking",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name="fk_invoice_company",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_invoice_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="invoice_pkey"),
        sa.UniqueConstraint("booking_id", name="uq_invoice_booking_one"),
    )
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.create_index("ix_invoice_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "ix_invoice_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_invoice_reference", ["reference"], unique=True)
        batch_op.create_index(
            "ix_invoice_company_status_due",
            ["company_id", "status", "due_date"],
            unique=False,
        )
        batch_op.create_index("ix_invoice_company_id", ["company_id"], unique=False)
        batch_op.create_index("ix_invoice_booking_id", ["booking_id"], unique=False)

    op.drop_table("invoice_reminders")
    op.drop_table("invoice_payments")
    op.drop_table("invoice_lines")
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoices_company_id"))
        batch_op.drop_index(batch_op.f("ix_invoices_client_id"))
        batch_op.drop_index("ix_invoice_status")
        batch_op.drop_index("ix_invoice_due_date")
        batch_op.drop_index("ix_invoice_company_period")

    op.drop_table("invoices")
    op.drop_table("invoice_sequences")
    op.drop_table("company_billing_settings")
    # ### end Alembic commands ###
