"""Add created_at to DispatchRun

Revision ID: 032c969a4b1e
Revises: 18e6b8d368d7
Create Date: 2025-09-22 02:27:32.994739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032c969a4b1e'
down_revision = '18e6b8d368d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_run', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
