"""add dispatch realtime models

Revision ID: 18e6b8d368d7
Revises: af64d3ec937a
Create Date: 2025-09-20 21:06:15.041362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e6b8d368d7'
down_revision = 'af64d3ec937a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'day', name='uq_dispatch_run_company_day')
    )
    with op.batch_alter_table('dispatch_run', schema=None) as batch_op:
        batch_op.create_index('ix_dispatch_run_company_day', ['company_id', 'day'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_run_company_id'), ['company_id'], unique=False)

    op.create_table('realtime_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('realtime_event', schema=None) as batch_op:
        batch_op.create_index('idx_realtime_event_company_type_time', ['company_id', 'event_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_event_company_id'), ['company_id'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_run_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'EN_ROUTE_PICKUP', 'ARRIVED_PICKUP', 'ONBOARD', 'EN_ROUTE_DROPOFF', 'ARRIVED_DROPOFF', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'REASSIGNED', name='assignment_status'), nullable=False),
    sa.Column('planned_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_dropoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_dropoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_dropoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispatch_run_id'], ['dispatch_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_run_id', 'booking_id', name='uq_assignment_run_booking')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_dispatch_run_id'), ['dispatch_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index('ix_assignment_driver_status', ['driver_id', 'status'], unique=False)

    op.create_table('driver_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('next_free_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_assignment_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_assignment_id'], ['assignment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_status_driver_id'), ['driver_id'], unique=True)
        batch_op.create_index('ix_driver_status_state_nextfree', ['state', 'next_free_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_status', schema=None) as batch_op:
        batch_op.drop_index('ix_driver_status_state_nextfree')
        batch_op.drop_index(batch_op.f('ix_driver_status_driver_id'))

    op.drop_table('driver_status')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index('ix_assignment_driver_status')
        batch_op.drop_index(batch_op.f('ix_assignment_driver_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_dispatch_run_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_booking_id'))

    op.drop_table('assignment')
    with op.batch_alter_table('realtime_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_realtime_event_company_id'))
        batch_op.drop_index('idx_realtime_event_company_type_time')

    op.drop_table('realtime_event')
    with op.batch_alter_table('dispatch_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_run_company_id'))
        batch_op.drop_index('ix_dispatch_run_company_day')

    op.drop_table('dispatch_run')
    # ### end Alembic commands ###
