"""initial schema (upper enums + aliases)

Revision ID: 19fc92c2ba30
Revises:
Create Date: 2025-10-04 09:23:56.758183

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "19fc92c2ba30"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("medical_establishment",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("type", sa.String(length=50), nullable=False),
    sa.Column("name", sa.String(length=0.200), nullable=False),
    sa.Column("display_name", sa.String(length=0.255), nullable=False),
    sa.Column("address", sa.String(length=0.255), nullable=False),
    sa.Column("lat", sa.Float(), nullable=False),
    sa.Column("lon", sa.Float(), nullable=False),
    sa.Column("aliases", sa.String(length=0.500), nullable=True),
    sa.Column("active", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.CheckConstraint("lat BETWEEN -90 AND 90", name="chk_med_estab_lat"),
    sa.CheckConstraint("lon BETWEEN -180 AND 180", name="chk_med_estab_lon"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("address", name="uq_med_estab_address"),
    sa.UniqueConstraint("name", name="uq_med_estab_name")
    )
    op.create_table("user",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("public_id", sa.String(length=36), nullable=False),
    sa.Column("username", sa.String(length=0.100), nullable=False),
    sa.Column("first_name", sa.String(length=0.100), nullable=True),
    sa.Column("last_name", sa.String(length=0.100), nullable=True),
    sa.Column("email", sa.String(length=0.100), nullable=True),
    sa.Column("phone", sa.String(length=20), nullable=True),
    sa.Column("address", sa.String(length=0.200), nullable=True),
    sa.Column("birth_date", sa.Date(), nullable=True),
    sa.Column("gender", sa.Enum("HOMME", "FEMME", "AUTRE", name="gender"), nullable=True),
    sa.Column("profile_image", sa.String(length=0.255), nullable=True),
    sa.Column("password", sa.String(length=0.255), nullable=False),
    sa.Column("role", sa.Enum("ADMIN", "CLIENT", "DRIVER", "COMPANY", name="user_role"), server_default="CLIENT", nullable=False),
    sa.Column("reset_token", sa.String(length=0.100), nullable=True),
    sa.Column("zip_code", sa.String(length=10), nullable=True),
    sa.Column("city", sa.String(length=0.100), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("force_password_change", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("reset_token")
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index("idx_public_id", ["public_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_public_id"), ["public_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table("company",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(length=0.100), nullable=False),
    sa.Column("address", sa.String(length=0.200), nullable=True),
    sa.Column("latitude", sa.Float(), nullable=True),
    sa.Column("longitude", sa.Float(), nullable=True),
    sa.Column("domicile_address_line1", sa.String(length=0.200), nullable=True),
    sa.Column("domicile_address_line2", sa.String(length=0.200), nullable=True),
    sa.Column("domicile_zip", sa.String(length=10), nullable=True),
    sa.Column("domicile_city", sa.String(length=0.100), nullable=True),
    sa.Column("domicile_country", sa.String(length=2), server_default="CH", nullable=True),
    sa.Column("contact_email", sa.String(length=0.100), nullable=True),
    sa.Column("contact_phone", sa.String(length=20), nullable=True),
    sa.Column("iban", sa.String(length=34), nullable=True),
    sa.Column("uid_ide", sa.String(length=20), nullable=True),
    sa.Column("billing_email", sa.String(length=0.100), nullable=True),
    sa.Column("billing_notes", sa.Text(), nullable=True),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("is_approved", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("service_area", sa.String(length=0.200), nullable=True),
    sa.Column("max_daily_bookings", sa.Integer(), server_default="50", nullable=True),
    sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("dispatch_enabled", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("is_partner", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("logo_url", sa.String(length=0.255), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_company_user", ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_company_iban"), ["iban"], unique=False)
        batch_op.create_index(batch_op.f("ix_company_uid_ide"), ["uid_ide"], unique=False)
        batch_op.create_index(batch_op.f("ix_company_user_id"), ["user_id"], unique=False)

    op.create_table("medical_service",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("establishment_id", sa.Integer(), nullable=False),
    sa.Column("category", sa.String(length=50), nullable=False),
    sa.Column("name", sa.String(length=0.200), nullable=False),
    sa.Column("slug", sa.String(length=0.200), nullable=True),
    sa.Column("address_line", sa.String(length=0.255), nullable=True),
    sa.Column("postcode", sa.String(length=16), nullable=True),
    sa.Column("city", sa.String(length=0.100), nullable=True),
    sa.Column("building", sa.String(length=0.120), nullable=True),
    sa.Column("floor", sa.String(length=60), nullable=True),
    sa.Column("site_note", sa.String(length=0.255), nullable=True),
    sa.Column("phone", sa.String(length=40), nullable=True),
    sa.Column("email", sa.String(length=0.120), nullable=True),
    sa.Column("lat", sa.Float(), nullable=True),
    sa.Column("lon", sa.Float(), nullable=True),
    sa.Column("active", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.CheckConstraint("lat IS NULL OR (lat BETWEEN -90 AND 90)", name="chk_med_service_lat"),
    sa.CheckConstraint("lon IS NULL OR (lon BETWEEN -180 AND 180)", name="chk_med_service_lon"),
    sa.ForeignKeyConstraint(["establishment_id"], ["medical_establishment.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("establishment_id", "name", name="uq_med_service_per_estab")
    )
    with op.batch_alter_table("medical_service", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_medical_service_establishment_id"), ["establishment_id"], unique=False)

    op.create_table("client",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("client_type", sa.Enum("SELF_SERVICE", "PRIVATE", "CORPORATE", name="client_type"), server_default="SELF_SERVICE", nullable=False),
    sa.Column("billing_address", sa.String(length=0.255), nullable=True),
    sa.Column("contact_email", sa.String(length=0.100), nullable=True),
    sa.Column("contact_phone", sa.String(length=50), nullable=True),
    sa.Column("domicile_address", sa.String(length=0.255), nullable=True),
    sa.Column("domicile_zip", sa.String(length=10), nullable=True),
    sa.Column("domicile_city", sa.String(length=0.100), nullable=True),
    sa.Column("door_code", sa.String(length=50), nullable=True),
    sa.Column("floor", sa.String(length=20), nullable=True),
    sa.Column("access_notes", sa.Text(), nullable=True),
    sa.Column("gp_name", sa.String(length=0.120), nullable=True),
    sa.Column("gp_phone", sa.String(length=50), nullable=True),
    sa.Column("default_billed_to_type", sa.String(length=50), server_default="patient", nullable=False),
    sa.Column("default_billed_to_company_id", sa.Integer(), nullable=True),
    sa.Column("default_billed_to_contact", sa.String(length=0.120), nullable=True),
    sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["default_billed_to_company_id"], ["company.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "company_id", name="uq_user_company")
    )
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.create_index("ix_client_company_active", ["company_id", "is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_client_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_client_company_user", ["company_id", "user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_client_user_id"), ["user_id"], unique=False)

    op.create_table("dispatch_run",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("day", sa.Date(), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name="ck_dispatch_run_status"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("company_id", "day", name="uq_dispatch_run_company_day")
    )
    with op.batch_alter_table("dispatch_run", schema=None) as batch_op:
        batch_op.create_index("ix_dispatch_run_company_day", ["company_id", "day"], unique=False)
        batch_op.create_index(batch_op.f("ix_dispatch_run_company_id"), ["company_id"], unique=False)

    op.create_table("driver",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("vehicle_assigned", sa.String(length=0.100), nullable=True),
    sa.Column("brand", sa.String(length=0.100), nullable=True),
    sa.Column("license_plate", sa.Text(), nullable=True),
    sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False),
    sa.Column("driver_type", sa.Enum("REGULAR", "EMERGENCY", name="driver_type"), server_default="REGULAR", nullable=False),
    sa.Column("latitude", sa.Float(), nullable=True),
    sa.Column("longitude", sa.Float(), nullable=True),
    sa.Column("last_position_update", sa.DateTime(timezone=True), nullable=True),
    sa.Column("driver_photo", sa.Text(), nullable=True),
    sa.Column("push_token", sa.String(length=0.255), nullable=True),
    sa.CheckConstraint("(latitude IS NULL OR (latitude BETWEEN -90 AND 90))", name="chk_driver_lat"),
    sa.CheckConstraint("(longitude IS NULL OR (longitude BETWEEN -180 AND 180))", name="chk_driver_lon"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("driver", schema=None) as batch_op:
        batch_op.create_index("ix_driver_company_active", ["company_id", "is_active", "is_available"], unique=False)
        batch_op.create_index(batch_op.f("ix_driver_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_driver_geo", ["company_id", "latitude", "longitude"], unique=False)
        batch_op.create_index(batch_op.f("ix_driver_push_token"), ["push_token"], unique=False)
        batch_op.create_index(batch_op.f("ix_driver_user_id"), ["user_id"], unique=True)

    op.create_table("favorite_place",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("label", sa.String(length=0.200), nullable=False),
    sa.Column("address", sa.String(length=0.255), nullable=False),
    sa.Column("lat", sa.Float(), nullable=False),
    sa.Column("lon", sa.Float(), nullable=False),
    sa.Column("tags", sa.String(length=0.200), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.CheckConstraint("lat BETWEEN -90 AND 90", name="chk_fav_lat"),
    sa.CheckConstraint("lon BETWEEN -180 AND 180", name="chk_fav_lon"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("company_id", "address", name="uq_fav_company_address")
    )
    with op.batch_alter_table("favorite_place", schema=None) as batch_op:
        batch_op.create_index("ix_fav_company_coords", ["company_id", "lat", "lon"], unique=False)
        batch_op.create_index("ix_fav_company_label", ["company_id", "label"], unique=False)
        batch_op.create_index(batch_op.f("ix_favorite_place_company_id"), ["company_id"], unique=False)

    op.create_table("message",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("sender_id", sa.Integer(), nullable=True),
    sa.Column("receiver_id", sa.Integer(), nullable=True),
    sa.Column("sender_role", sa.Enum("DRIVER", "COMPANY", name="sender_role"), nullable=False),
    sa.Column("content", sa.Text(), nullable=False),
    sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("is_read", sa.Boolean(), nullable=False),
    sa.CheckConstraint("sender_role IN ('DRIVER','COMPANY')", name="check_sender_role_valid"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["receiver_id"], ["user.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["sender_id"], ["user.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_message_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_message_receiver_id"), ["receiver_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_message_sender_id"), ["sender_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_message_timestamp"), ["timestamp"], unique=False)
        batch_op.create_index("ix_msg_company_receiver_unread_ts", ["company_id", "receiver_id", "is_read", "timestamp"], unique=False)

    op.create_table("realtime_event",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("event_type", sa.Enum("LOCATION_UPDATE", "STATUS_CHANGE", "ASSIGNMENT_DELTA", "DELAY_DETECTED", name="realtime_event_type"), nullable=False),
    sa.Column("entity_type", sa.Enum("DRIVER", "BOOKING", "ASSIGNMENT", name="realtime_entity_type"), nullable=False),
    sa.Column("entity_id", sa.Integer(), nullable=False),
    sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.CheckConstraint("entity_id > 0", name="ck_realtime_entity_id_positive"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("realtime_event", schema=None) as batch_op:
        batch_op.create_index("idx_realtime_event_company_type_time", ["company_id", "event_type", "timestamp"], unique=False)
        batch_op.create_index("idx_realtime_event_entity_time", ["entity_type", "entity_id", "timestamp"], unique=False)
        batch_op.create_index(batch_op.f("ix_realtime_event_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_realtime_event_data_gin", ["data"], unique=False, postgresql_using="gin")

    op.create_table("vehicle",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("model", sa.String(length=0.120), nullable=False),
    sa.Column("license_plate", sa.String(length=20), nullable=False),
    sa.Column("year", sa.Integer(), nullable=True),
    sa.Column("vin", sa.String(length=32), nullable=True),
    sa.Column("seats", sa.Integer(), nullable=True),
    sa.Column("wheelchair_accessible", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("insurance_expires_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("inspection_expires_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.CheckConstraint("seats IS NULL OR seats >= 0", name="chk_vehicle_seats"),
    sa.CheckConstraint("year IS NULL OR year BETWEEN 1950 AND 2100", name="chk_vehicle_year"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("company_id", "license_plate", name="uq_company_plate")
    )
    with op.batch_alter_table("vehicle", schema=None) as batch_op:
        batch_op.create_index("ix_vehicle_company_active", ["company_id", "is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_vehicle_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vehicle_license_plate"), ["license_plate"], unique=False)

    op.create_table("booking",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("customer_name", sa.String(length=0.100), nullable=False),
    sa.Column("pickup_location", sa.String(length=0.200), nullable=False),
    sa.Column("dropoff_location", sa.String(length=0.200), nullable=False),
    sa.Column("booking_type", sa.String(length=0.200), server_default="standard", nullable=False),
    sa.Column("scheduled_time", sa.DateTime(), nullable=True),
    sa.Column("amount", sa.Float(), nullable=False),
    sa.Column("status", sa.Enum("PENDING", "ACCEPTED", "ASSIGNED", "EN_ROUTE", "IN_PROGRESS", "COMPLETED", "RETURN_COMPLETED", "CANCELED", name="booking_status"), server_default="PENDING", nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("rejected_by", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column("duration_seconds", sa.Integer(), nullable=True),
    sa.Column("distance_meters", sa.Integer(), nullable=True),
    sa.Column("client_id", sa.Integer(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=True),
    sa.Column("driver_id", sa.Integer(), nullable=True),
    sa.Column("is_round_trip", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.Column("is_return", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.Column("boarded_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("parent_booking_id", sa.Integer(), nullable=True),
    sa.Column("medical_facility", sa.String(length=0.200), nullable=True),
    sa.Column("doctor_name", sa.String(length=0.200), nullable=True),
    sa.Column("hospital_service", sa.String(length=0.100), nullable=True),
    sa.Column("notes_medical", sa.Text(), nullable=True),
    sa.Column("is_urgent", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.Column("pickup_lat", sa.Float(), nullable=True),
    sa.Column("pickup_lon", sa.Float(), nullable=True),
    sa.Column("dropoff_lat", sa.Float(), nullable=True),
    sa.Column("dropoff_lon", sa.Float(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("billed_to_type", sa.String(length=50), server_default="patient", nullable=False),
    sa.Column("billed_to_company_id", sa.Integer(), nullable=True),
    sa.Column("billed_to_contact", sa.String(length=0.120), nullable=True),
    sa.CheckConstraint("dropoff_lat IS NULL OR (dropoff_lat BETWEEN -90 AND 90)", name="chk_booking_drop_lat"),
    sa.CheckConstraint("dropoff_lon IS NULL OR (dropoff_lon BETWEEN -180 AND 180)", name="chk_booking_drop_lon"),
    sa.CheckConstraint("pickup_lat IS NULL OR (pickup_lat BETWEEN -90 AND 90)", name="chk_booking_pickup_lat"),
    sa.CheckConstraint("pickup_lon IS NULL OR (pickup_lon BETWEEN -180 AND 180)", name="chk_booking_pickup_lon"),
    sa.ForeignKeyConstraint(["billed_to_company_id"], ["company.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["parent_booking_id"], ["booking.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_booking_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_booking_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_booking_company_scheduled", ["company_id", "scheduled_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_booking_driver_id"), ["driver_id"], unique=False)
        batch_op.create_index("ix_booking_driver_status", ["driver_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_booking_status"), ["status"], unique=False)
        batch_op.create_index("ix_booking_status_scheduled", ["status", "scheduled_time"], unique=False)

    op.create_table("driver_vacations",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("driver_id", sa.Integer(), nullable=False),
    sa.Column("start_date", sa.Date(), nullable=False),
    sa.Column("end_date", sa.Date(), nullable=False),
    sa.Column("vacation_type", sa.Enum("VACANCES", "MALADIE", "CONGES", "AUTRE", name="vacation_type"), server_default="VACANCES", nullable=False),
    sa.CheckConstraint("start_date <= end_date", name="chk_vacation_dates_order"),
    sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("driver_id", "start_date", "end_date", "vacation_type", name="uq_vacation_exact_period")
    )
    with op.batch_alter_table("driver_vacations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_driver_vacations_driver_id"), ["driver_id"], unique=False)
        batch_op.create_index("ix_vacation_driver_end", ["driver_id", "end_date"], unique=False)
        batch_op.create_index("ix_vacation_driver_start", ["driver_id", "start_date"], unique=False)

    op.create_table("driver_working_config",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("driver_id", sa.Integer(), nullable=False),
    sa.Column("earliest_start", sa.Integer(), server_default="360", nullable=False),
    sa.Column("latest_start", sa.Integer(), server_default="600", nullable=False),
    sa.Column("total_working_minutes", sa.Integer(), server_default="510", nullable=False),
    sa.Column("break_duration", sa.Integer(), server_default="60", nullable=False),
    sa.Column("break_earliest", sa.Integer(), server_default="600", nullable=False),
    sa.Column("break_latest", sa.Integer(), server_default="900", nullable=False),
    sa.CheckConstraint("break_duration <= total_working_minutes", name="chk_dwc_break_vs_total"),
    sa.CheckConstraint("break_duration BETWEEN 0 AND 1440", name="chk_dwc_break_dur"),
    sa.CheckConstraint("break_earliest < break_latest", name="chk_dwc_break_window"),
    sa.CheckConstraint("break_earliest BETWEEN 0 AND 1440", name="chk_dwc_break_earliest"),
    sa.CheckConstraint("break_latest BETWEEN 0 AND 1440", name="chk_dwc_break_latest"),
    sa.CheckConstraint("earliest_start < latest_start", name="chk_dwc_start_window"),
    sa.CheckConstraint("earliest_start BETWEEN 0 AND 1440", name="chk_dwc_earliest"),
    sa.CheckConstraint("latest_start BETWEEN 0 AND 1440", name="chk_dwc_latest"),
    sa.CheckConstraint("total_working_minutes BETWEEN 0 AND 1440", name="chk_dwc_total"),
    sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("driver_id", name="uq_dwc_driver")
    )
    with op.batch_alter_table("driver_working_config", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_driver_working_config_driver_id"), ["driver_id"], unique=True)
        batch_op.create_index("ix_dwc_driver", ["driver_id"], unique=False)

    op.create_table("assignment",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("dispatch_run_id", sa.Integer(), nullable=False),
    sa.Column("booking_id", sa.Integer(), nullable=False),
    sa.Column("driver_id", sa.Integer(), nullable=True),
    sa.Column("status", sa.Enum("SCHEDULED", "EN_ROUTE_PICKUP", "ARRIVED_PICKUP", "ONBOARD", "EN_ROUTE_DROPOFF", "ARRIVED_DROPOFF", "COMPLETED", "CANCELLED", "NO_SHOW", "REASSIGNED", name="assignment_status"), nullable=False),
    sa.Column("planned_pickup_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("planned_dropoff_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("actual_pickup_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("actual_dropoff_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("eta_pickup_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("eta_dropoff_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("delay_seconds", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("delay_seconds >= 0", name="ck_assignment_delay_nonneg"),
    sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["dispatch_run_id"], ["dispatch_run.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("dispatch_run_id", "booking_id", name="uq_assignment_run_booking")
    )
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assignment_booking_id"), ["booking_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_assignment_dispatch_run_id"), ["dispatch_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_assignment_driver_id"), ["driver_id"], unique=False)
        batch_op.create_index("ix_assignment_driver_status", ["driver_id", "status"], unique=False)

    op.create_table("invoice",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("reference", sa.String(length=32), nullable=False),
    sa.Column("amount", sa.Float(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("booking_id", sa.Integer(), nullable=True),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("details", sa.Text(), nullable=True),
    sa.Column("pdf_url", sa.String(length=0.255), nullable=True),
    sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
    sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("status", sa.Enum("UNPAID", "PAID", "CANCELED", name="invoice_status"), server_default="UNPAID", nullable=False),
    sa.CheckConstraint("amount > 0", name="chk_invoice_amount_positive"),
    sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], name="fk_invoice_booking", ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], name="fk_invoice_company", ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_invoice_user", ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("booking_id", name="uq_invoice_booking_one")
    )
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invoice_booking_id"), ["booking_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoice_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_invoice_company_status_due", ["company_id", "status", "due_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoice_reference"), ["reference"], unique=True)
        batch_op.create_index("ix_invoice_user_created", ["user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoice_user_id"), ["user_id"], unique=False)

    op.create_table("payment",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("amount", sa.Float(), nullable=False),
    sa.Column("date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("method", sa.Enum("credit_card", "paypal", "bank_transfer", "cash", name="payment_method"), nullable=False),
    sa.Column("status", sa.Enum("PENDING", "COMPLETED", "FAILED", name="payment_status"), server_default="PENDING", nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("client_id", sa.Integer(), nullable=False),
    sa.Column("booking_id", sa.Integer(), nullable=False),
    sa.CheckConstraint("amount > 0", name="chk_payment_amount_positive"),
    sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_booking_id"), ["booking_id"], unique=False)
        batch_op.create_index("ix_payment_booking_status", ["booking_id", "status"], unique=False)
        batch_op.create_index("ix_payment_client_date", ["client_id", "date"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_user_id"), ["user_id"], unique=False)

    op.create_table("driver_status",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("driver_id", sa.Integer(), nullable=False),
    sa.Column("state", sa.Enum("AVAILABLE", "BUSY", "OFFLINE", name="driver_state"), server_default="AVAILABLE", nullable=False),
    sa.Column("latitude", sa.Float(), nullable=True),
    sa.Column("longitude", sa.Float(), nullable=True),
    sa.Column("heading", sa.Float(), nullable=True),
    sa.Column("speed", sa.Float(), nullable=True),
    sa.Column("next_free_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("current_assignment_id", sa.Integer(), nullable=True),
    sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("heading IS NULL OR (heading >= 0 AND heading <= 360)", name="ck_driver_status_heading"),
    sa.CheckConstraint("latitude IS NULL OR (latitude BETWEEN -90 AND 90)", name="ck_driver_status_lat"),
    sa.CheckConstraint("longitude IS NULL OR (longitude BETWEEN -180 AND 180)", name="ck_driver_status_lon"),
    sa.CheckConstraint("speed IS NULL OR speed >= 0", name="ck_driver_status_speed"),
    sa.ForeignKeyConstraint(["current_assignment_id"], ["assignment.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("driver_status", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_driver_status_driver_id"), ["driver_id"], unique=True)
        batch_op.create_index("ix_driver_status_state_nextfree", ["state", "next_free_at"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("driver_status", schema=None) as batch_op:
        batch_op.drop_index("ix_driver_status_state_nextfree")
        batch_op.drop_index(batch_op.f("ix_driver_status_driver_id"))

    op.drop_table("driver_status")
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_user_id"))
        batch_op.drop_index(batch_op.f("ix_payment_client_id"))
        batch_op.drop_index("ix_payment_client_date")
        batch_op.drop_index("ix_payment_booking_status")
        batch_op.drop_index(batch_op.f("ix_payment_booking_id"))

    op.drop_table("payment")
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoice_user_id"))
        batch_op.drop_index("ix_invoice_user_created")
        batch_op.drop_index(batch_op.f("ix_invoice_reference"))
        batch_op.drop_index("ix_invoice_company_status_due")
        batch_op.drop_index(batch_op.f("ix_invoice_company_id"))
        batch_op.drop_index(batch_op.f("ix_invoice_booking_id"))

    op.drop_table("invoice")
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_index("ix_assignment_driver_status")
        batch_op.drop_index(batch_op.f("ix_assignment_driver_id"))
        batch_op.drop_index(batch_op.f("ix_assignment_dispatch_run_id"))
        batch_op.drop_index(batch_op.f("ix_assignment_booking_id"))

    op.drop_table("assignment")
    with op.batch_alter_table("driver_working_config", schema=None) as batch_op:
        batch_op.drop_index("ix_dwc_driver")
        batch_op.drop_index(batch_op.f("ix_driver_working_config_driver_id"))

    op.drop_table("driver_working_config")
    with op.batch_alter_table("driver_vacations", schema=None) as batch_op:
        batch_op.drop_index("ix_vacation_driver_start")
        batch_op.drop_index("ix_vacation_driver_end")
        batch_op.drop_index(batch_op.f("ix_driver_vacations_driver_id"))

    op.drop_table("driver_vacations")
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_index("ix_booking_status_scheduled")
        batch_op.drop_index(batch_op.f("ix_booking_status"))
        batch_op.drop_index("ix_booking_driver_status")
        batch_op.drop_index(batch_op.f("ix_booking_driver_id"))
        batch_op.drop_index("ix_booking_company_scheduled")
        batch_op.drop_index(batch_op.f("ix_booking_company_id"))
        batch_op.drop_index(batch_op.f("ix_booking_client_id"))

    op.drop_table("booking")
    with op.batch_alter_table("vehicle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vehicle_license_plate"))
        batch_op.drop_index(batch_op.f("ix_vehicle_company_id"))
        batch_op.drop_index("ix_vehicle_company_active")

    op.drop_table("vehicle")
    with op.batch_alter_table("realtime_event", schema=None) as batch_op:
        batch_op.drop_index("ix_realtime_event_data_gin", postgresql_using="gin")
        batch_op.drop_index(batch_op.f("ix_realtime_event_company_id"))
        batch_op.drop_index("idx_realtime_event_entity_time")
        batch_op.drop_index("idx_realtime_event_company_type_time")

    op.drop_table("realtime_event")
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index("ix_msg_company_receiver_unread_ts")
        batch_op.drop_index(batch_op.f("ix_message_timestamp"))
        batch_op.drop_index(batch_op.f("ix_message_sender_id"))
        batch_op.drop_index(batch_op.f("ix_message_receiver_id"))
        batch_op.drop_index(batch_op.f("ix_message_company_id"))

    op.drop_table("message")
    with op.batch_alter_table("favorite_place", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorite_place_company_id"))
        batch_op.drop_index("ix_fav_company_label")
        batch_op.drop_index("ix_fav_company_coords")

    op.drop_table("favorite_place")
    with op.batch_alter_table("driver", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_driver_user_id"))
        batch_op.drop_index(batch_op.f("ix_driver_push_token"))
        batch_op.drop_index("ix_driver_geo")
        batch_op.drop_index(batch_op.f("ix_driver_company_id"))
        batch_op.drop_index("ix_driver_company_active")

    op.drop_table("driver")
    with op.batch_alter_table("dispatch_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dispatch_run_company_id"))
        batch_op.drop_index("ix_dispatch_run_company_day")

    op.drop_table("dispatch_run")
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_user_id"))
        batch_op.drop_index("ix_client_company_user")
        batch_op.drop_index(batch_op.f("ix_client_company_id"))
        batch_op.drop_index("ix_client_company_active")

    op.drop_table("client")
    with op.batch_alter_table("medical_service", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_service_establishment_id"))

    op.drop_table("medical_service")
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_user_id"))
        batch_op.drop_index(batch_op.f("ix_company_uid_ide"))
        batch_op.drop_index(batch_op.f("ix_company_iban"))

    op.drop_table("company")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_public_id"))
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.drop_index("idx_public_id")

    op.drop_table("user")
    op.drop_table("medical_establishment")
    # ### end Alembic commands ###
