"""add billing_strategy to invoices

Revision ID: 1ad728d75597
Revises: 2d80b4b86bd2
Create Date: 2026-01-24 20:18:52.568470

Idempotent: 3cdf4454ec3c (invoice_billing_strategy_s2_v1) peut déjà avoir ajouté
billing_strategy et billed_to_company_id. On n'ajoute que si absents.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect


revision = "1ad728d75597"
down_revision = "2d80b4b86bd2"
branch_labels = None
depends_on = None


def _invoices_has_column(conn, name: str) -> bool:
    insp = inspect(conn)
    cols = [c["name"] for c in insp.get_columns("invoices")]
    return name in cols


def _invoices_has_index(conn, index_name: str) -> bool:
    insp = inspect(conn)
    return any(idx["name"] == index_name for idx in insp.get_indexes("invoices"))


def upgrade():
    # Idempotent: ne faire que si les colonnes/Index/FK n'existent pas déjà
    # (3cdf4454ec3c peut les avoir créés).
    conn = op.get_bind()
    invoice_billing_strategy_enum = postgresql.ENUM(
        "s1_patient",
        "s2_clinic_monthly",
        name="invoice_billing_strategy",
    )
    invoice_billing_strategy_enum.create(conn, checkfirst=True)

    if not _invoices_has_column(conn, "billing_strategy"):
        op.add_column(
            "invoices",
            sa.Column(
                "billing_strategy",
                sa.Enum(
                    "s1_patient",
                    "s2_clinic_monthly",
                    name="invoice_billing_strategy",
                ),
                server_default="s1_patient",
                nullable=False,
            ),
        )
    if not _invoices_has_column(conn, "billed_to_company_id"):
        op.add_column(
            "invoices",
            sa.Column("billed_to_company_id", sa.Integer(), nullable=True),
        )
    if not _invoices_has_index(conn, "ix_invoices_billed_to_company_id"):
        op.create_index(
            op.f("ix_invoices_billed_to_company_id"),
            "invoices",
            ["billed_to_company_id"],
            unique=False,
        )
    # FK: créer seulement si l'index existe (donc on vient de le créer ou il existait)
    # On vérifie via les FK existantes sur la table invoices
    insp = inspect(conn)
    fks = insp.get_foreign_keys("invoices")
    has_billed_to_company_fk = any(
        "billed_to_company_id" in (fk.get("constrained_columns") or []) for fk in fks
    )
    if not has_billed_to_company_fk:
        op.create_foreign_key(
            None,
            "invoices",
            "company",
            ["billed_to_company_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_index(op.f("ix_invoices_billed_to_company_id"), table_name="invoices")
    op.drop_column("invoices", "billed_to_company_id")
    op.drop_column("invoices", "billing_strategy")

    invoice_billing_strategy_enum = postgresql.ENUM(
        "s1_patient",
        "s2_clinic_monthly",
        name="invoice_billing_strategy",
    )
    invoice_billing_strategy_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
