"""add billing_strategy to invoices

Revision ID: 1ad728d75597
Revises: 2d80b4b86bd2
Create Date: 2026-01-24 20:18:52.568470

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "1ad728d75597"
down_revision = "2d80b4b86bd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    invoice_billing_strategy_enum = postgresql.ENUM(
        "s1_patient",
        "s2_clinic_monthly",
        name="invoice_billing_strategy",
    )
    invoice_billing_strategy_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "invoices",
        sa.Column(
            "billing_strategy",
            sa.Enum("s1_patient", "s2_clinic_monthly", name="invoice_billing_strategy"),
            server_default="s1_patient",
            nullable=False,
        ),
    )
    op.add_column(
        "invoices", sa.Column("billed_to_company_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_invoices_billed_to_company_id"),
        "invoices",
        ["billed_to_company_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "invoices",
        "company",
        ["billed_to_company_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_index(op.f("ix_invoices_billed_to_company_id"), table_name="invoices")
    op.drop_column("invoices", "billed_to_company_id")
    op.drop_column("invoices", "billing_strategy")

    invoice_billing_strategy_enum = postgresql.ENUM(
        "s1_patient",
        "s2_clinic_monthly",
        name="invoice_billing_strategy",
    )
    invoice_billing_strategy_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
