
"""email signature form fields

Revision ID: 1bbbda3dd455
Revises: 20260126233819
Create Date: 2026-01-27 03:06:19.966855

"""
from alembic import op
import sqlalchemy as sa


revision = "1bbbda3dd455"
down_revision = '20260126233819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_billing_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_signature_mode', sa.String(length=10), server_default='form', nullable=False))
        batch_op.add_column(sa.Column('email_signature_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature_company', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature_phone_main', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('signature_phone_mobile', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('signature_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature_website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature_address_line', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature_zip', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('signature_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_signature_html_template', sa.Text(), nullable=True))

    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_reminder'))
        batch_op.create_index(batch_op.f('ix_invoice_payments_reminder_id'), ['reminder_id'], unique=False)

    with op.batch_alter_table('invoice_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_reminders_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_reminders_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_reminders_invoice_status'), ['invoice_id', 'status'], unique=False)

    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_reminder_id'))
        batch_op.create_index(batch_op.f('ix_invoice_payments_reminder'), ['reminder_id'], unique=False)

    with op.batch_alter_table('company_billing_settings', schema=None) as batch_op:
        batch_op.drop_column('email_signature_html_template')
        batch_op.drop_column('signature_city')
        batch_op.drop_column('signature_zip')
        batch_op.drop_column('signature_address_line')
        batch_op.drop_column('signature_website')
        batch_op.drop_column('signature_email')
        batch_op.drop_column('signature_phone_mobile')
        batch_op.drop_column('signature_phone_main')
        batch_op.drop_column('signature_company')
        batch_op.drop_column('signature_title')
        batch_op.drop_column('signature_name')
        batch_op.drop_column('email_signature_text')
        batch_op.drop_column('email_signature_mode')

    # ### end Alembic commands ###

