"""add brevo email configuration

Revision ID: 20260110_add_brevo
Revises: 7b9ef6f2dc08
Create Date: 2026-01-10 00:04:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260110_add_brevo"
down_revision = "7b9ef6f2dc08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_billing_settings",
        sa.Column("from_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "company_billing_settings",
        sa.Column(
            "domain_verified", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.add_column(
        "company_billing_settings",
        sa.Column("domain_dns_records", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_billing_settings", "domain_dns_records")
    op.drop_column("company_billing_settings", "domain_verified")
    op.drop_column("company_billing_settings", "from_name")
    # ### end Alembic commands ###
