
"""restore refresh_token unique index

Revision ID: 292d4fc6604a
Revises: 49ff432aafec
Create Date: 2026-01-24 21:37:06.197842

"""
from alembic import op
import sqlalchemy as sa


revision = "292d4fc6604a"
down_revision = '49ff432aafec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=False)

    # ### end Alembic commands ###

