"""add_contact_fields_to_client_billing_parties

Revision ID: 2d80b4b86bd2
Revises: b59281cc564a
Create Date: 2026-01-24 13:26:38.686236

"""
from alembic import op
import sqlalchemy as sa


revision = "2d80b4b86bd2"
down_revision = "b59281cc564a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_billing_parties", schema=None) as batch_op:
        batch_op.add_column(sa.Column("contact_name", sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column("contact_email", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("contact_phone", sa.String(length=50), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_billing_parties", schema=None) as batch_op:
        batch_op.drop_column("contact_phone")
        batch_op.drop_column("contact_email")
        batch_op.drop_column("contact_name")

    # ### end Alembic commands ###
