"""invoice_billing_strategy_s2_v1

Revision ID: 3cdf4454ec3c
Revises: 8517da8372d2
Create Date: 2026-01-21 11:07:49.996190

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "3cdf4454ec3c"
down_revision = "8517da8372d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    invoice_billing_strategy_enum = postgresql.ENUM(
        "s1_patient",
        "s2_clinic_monthly",
        name="invoice_billing_strategy",
    )
    invoice_billing_strategy_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "invoices",
        sa.Column(
            "billing_strategy",
            sa.Enum("s1_patient", "s2_clinic_monthly", name="invoice_billing_strategy"),
            server_default="s1_patient",
            nullable=False,
        ),
    )
    op.add_column(
        "invoices", sa.Column("billed_to_company_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_invoices_billed_to_company_id"),
        "invoices",
        ["billed_to_company_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "invoices",
        "company",
        ["billed_to_company_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Unicité S2: une seule facture par (company_id, clinic_payeur, période) en S2
    op.create_index(
        "uq_invoices_s2_clinic_monthly_company_clinic_period",
        "invoices",
        ["company_id", "billed_to_company_id", "period_year", "period_month"],
        unique=True,
        postgresql_where=sa.text(
            "billing_strategy = 's2_clinic_monthly' AND billed_to_company_id IS NOT NULL"
        ),
    )
    # NOTE: Alembic a détecté un changement d'unicité sur refresh_token.token_hash.
    # Ce n'est pas lié à la facturation S2, on ne le modifie pas ici.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_index(
        "uq_invoices_s2_clinic_monthly_company_clinic_period",
        table_name="invoices",
        postgresql_where=sa.text(
            "billing_strategy = 's2_clinic_monthly' AND billed_to_company_id IS NOT NULL"
        ),
    )
    op.drop_index(op.f("ix_invoices_billed_to_company_id"), table_name="invoices")
    op.drop_column("invoices", "billed_to_company_id")
    op.drop_column("invoices", "billing_strategy")

    invoice_billing_strategy_enum = postgresql.ENUM(
        "s1_patient",
        "s2_clinic_monthly",
        name="invoice_billing_strategy",
    )
    invoice_billing_strategy_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
