"""make_billing_settings_fields_nullable

Revision ID: 3f7695e18b7d
Revises: 02e0994e702b
Create Date: 2025-10-09 08:46:14.417595

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f7695e18b7d"
down_revision = "02e0994e702b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_billing_settings", schema=None) as batch_op:
        batch_op.alter_column("payment_terms_days", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("overdue_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True)
        batch_op.alter_column("reminder1_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True)
        batch_op.alter_column("reminder2_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True)
        batch_op.alter_column("reminder3_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_billing_settings", schema=None) as batch_op:
        batch_op.alter_column("reminder3_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
        batch_op.alter_column("reminder2_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
        batch_op.alter_column("reminder1_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
        batch_op.alter_column("overdue_fee", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
        batch_op.alter_column("payment_terms_days", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
