"""add transport vouchers

Revision ID: 49ff432aafec
Revises: 1ad728d75597
Create Date: 2026-01-24 21:26:17.060122

Idempotent (PostgreSQL): utilisation de table_exists/index_exists via
information_schema/pg_indexes pour éviter DuplicateTable/DuplicateObject
quand des tables existent déjà (ex: DB à e34565d5b10d mais tables créées
par d'autres branches / runs partiels).
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text


revision = "49ff432aafec"
down_revision = "1ad728d75597"
branch_labels = None
depends_on = None


def _table_exists(bind, name: str, schema: str = "public") -> bool:
    """Vrai si la table existe (PostgreSQL information_schema)."""
    r = bind.execute(
        text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = :s AND table_name = :t)"
        ),
        {"s": schema, "t": name},
    )
    return r.scalar()


def _index_exists(bind, index_name: str, schema: str = "public") -> bool:
    """Vrai si l'index existe (PostgreSQL pg_indexes)."""
    r = bind.execute(
        text(
            "SELECT EXISTS (SELECT 1 FROM pg_indexes "
            "WHERE schemaname = :s AND indexname = :n)"
        ),
        {"s": schema, "n": index_name},
    )
    return r.scalar()


def _constraint_exists(
    bind, table_name: str, constraint_name: str, schema: str = "public"
) -> bool:
    """Vrai si la contrainte existe (PostgreSQL information_schema)."""
    r = bind.execute(
        text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.table_constraints "
            "WHERE table_schema = :s AND table_name = :t AND constraint_name = :c)"
        ),
        {"s": schema, "t": table_name, "c": constraint_name},
    )
    return r.scalar()


def _get_fk_constraint_name(
    bind,
    table_name: str,
    column_name: str,
    referred_table: str,
    schema: str = "public",
    referred_column: str = "id",
):
    """Nom de la FK (table.col → referred_table.referred_column), ou None. Détection par définition."""
    r = bind.execute(
        text(
            "SELECT tc.constraint_name FROM information_schema.table_constraints tc "
            "JOIN information_schema.key_column_usage kcu "
            "  ON tc.constraint_name = kcu.constraint_name "
            "  AND tc.table_schema = kcu.table_schema AND tc.table_name = kcu.table_name "
            "JOIN information_schema.constraint_column_usage ccu "
            "  ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema "
            "WHERE tc.constraint_type = 'FOREIGN KEY' "
            "  AND tc.table_schema = :s AND tc.table_name = :t AND kcu.column_name = :col "
            "  AND ccu.table_schema = :s AND ccu.table_name = :ref_t AND ccu.column_name = :ref_col "
            "LIMIT 1"
        ),
        {
            "s": schema,
            "t": table_name,
            "col": column_name,
            "ref_t": referred_table,
            "ref_col": referred_column,
        },
    )
    row = r.fetchone()
    return row[0] if row else None


def _fk_exists(
    bind, table_name: str, column_name: str, referred_table: str, schema: str = "public"
):
    """Vrai si une FK existe de (table, column) vers (referred_table, id)."""
    return (
        _get_fk_constraint_name(bind, table_name, column_name, referred_table, schema)
        is not None
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if not _table_exists(conn, "password_history"):
        op.create_table(
            "password_history",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("password_hash", sa.String(length=255), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("password_history", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_password_history_created_at"),
                ["created_at"],
                unique=False,
            )
            batch_op.create_index(
                "ix_password_history_user_created",
                ["user_id", "created_at"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_password_history_user_id"), ["user_id"], unique=False
            )

    if not _table_exists(conn, "billing_audit_logs"):
        op.create_table(
            "billing_audit_logs",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("company_id", sa.Integer(), nullable=False),
            sa.Column("booking_id", sa.Integer(), nullable=False),
            sa.Column("actor_user_id", sa.Integer(), nullable=True),
            sa.Column("action", sa.Text(), nullable=False),
            sa.Column("reason", sa.Text(), nullable=True),
            sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["actor_user_id"], ["user.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("billing_audit_logs", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_billing_audit_logs_actor_user_id"),
                ["actor_user_id"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_billing_audit_logs_booking_id"),
                ["booking_id"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_billing_audit_logs_company_id"),
                ["company_id"],
                unique=False,
            )

    if not _table_exists(conn, "company_billing_profile"):
        op.create_table(
            "company_billing_profile",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("company_id", sa.Integer(), nullable=False),
            sa.Column(
                "legal_name",
                sa.String(length=200),
                nullable=False,
                comment="Nom légal de l'entreprise pour factures",
            ),
            sa.Column(
                "brand_name",
                sa.String(length=200),
                nullable=True,
                comment="Nom commercial (si différent du nom légal)",
            ),
            sa.Column(
                "uid_ide",
                sa.String(length=20),
                nullable=False,
                comment="Numéro IDE/UID suisse (format: CHE-XXX.XXX.XXX)",
            ),
            sa.Column(
                "street_name",
                sa.String(length=70),
                nullable=False,
                comment="Nom de rue (sans numéro)",
            ),
            sa.Column(
                "building_number",
                sa.String(length=16),
                nullable=False,
                comment="Numéro de bâtiment (peut contenir lettres: 12A)",
            ),
            sa.Column(
                "postal_code",
                sa.String(length=16),
                nullable=False,
                comment="Code postal (4 chiffres pour Suisse)",
            ),
            sa.Column("city", sa.String(length=35), nullable=False, comment="Ville"),
            sa.Column(
                "country_code",
                sa.String(length=2),
                nullable=False,
                comment="Code pays ISO 3166-1 alpha-2",
            ),
            sa.Column(
                "billing_email",
                sa.String(length=100),
                nullable=False,
                comment="Email pour envoi factures",
            ),
            sa.Column(
                "billing_phone",
                sa.String(length=20),
                nullable=False,
                comment="Téléphone facturation (format international recommandé)",
            ),
            sa.Column(
                "vat_registered",
                sa.Boolean(),
                nullable=False,
                comment="Entreprise assujettie à la TVA",
            ),
            sa.Column(
                "vat_number",
                sa.String(length=50),
                nullable=True,
                comment="Numéro TVA (si assujetti)",
            ),
            sa.Column(
                "vat_rate",
                sa.Numeric(precision=5, scale=2),
                nullable=True,
                comment="Taux TVA par défaut (ex: 7.7 pour 7.7%)",
            ),
            sa.Column(
                "iban",
                sa.String(length=200),
                nullable=False,
                comment="IBAN chiffré (format CHxx xxxx xxxx xxxx xxxx x)",
            ),
            sa.Column(
                "qr_iban",
                sa.String(length=200),
                nullable=True,
                comment="QR-IBAN chiffré (uniquement si références QRR)",
            ),
            sa.Column(
                "payment_reference_mode",
                sa.String(length=10),
                nullable=False,
                comment="Mode référence paiement: NONE, SCOR (ISO 11649), QRR (ESR)",
            ),
            sa.Column(
                "creditor_reference_base",
                sa.String(length=20),
                nullable=True,
                comment="Base pour générer références QRR (si mode=QRR)",
            ),
            sa.Column(
                "payment_terms_days",
                sa.Integer(),
                nullable=False,
                comment="Délai de paiement en jours",
            ),
            sa.Column(
                "overdue_fee",
                sa.Numeric(precision=10, scale=2),
                nullable=False,
                comment="Frais de retard (CHF)",
            ),
            sa.Column(
                "legal_footer",
                sa.Text(),
                nullable=True,
                comment="Texte légal pied de page facture",
            ),
            sa.Column(
                "is_address_validated",
                sa.Boolean(),
                nullable=False,
                comment="Adresse validée (structure + existence)",
            ),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("company_billing_profile", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_company_billing_profile_company_id"),
                ["company_id"],
                unique=True,
            )
            batch_op.create_index(
                batch_op.f("ix_company_billing_profile_uid_ide"),
                ["uid_ide"],
                unique=False,
            )

    if not _table_exists(conn, "device_tokens"):
        op.create_table(
            "device_tokens",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("driver_id", sa.Integer(), nullable=False),
            sa.Column("token", sa.String(length=255), nullable=False),
            sa.Column("device_id", sa.String(length=255), nullable=True),
            sa.Column("platform", sa.String(length=20), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("device_tokens", schema=None) as batch_op:
            batch_op.create_index(
                "ix_device_tokens_driver_active",
                ["driver_id", "is_active"],
                unique=False,
            )
            batch_op.create_index(
                "ix_device_tokens_driver_id", ["driver_id"], unique=False
            )
            batch_op.create_index("ix_device_tokens_token", ["token"], unique=False)

    if not _table_exists(conn, "transport_vouchers"):
        op.create_table(
            "transport_vouchers",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("company_id", sa.Integer(), nullable=False),
            sa.Column("client_id", sa.Integer(), nullable=False),
            sa.Column("booking_id", sa.Integer(), nullable=True),
            sa.Column("billing_party_id", sa.Integer(), nullable=True),
            sa.Column(
                "type", sa.String(length=50), server_default="clinic", nullable=False
            ),
            sa.Column(
                "status", sa.String(length=50), server_default="draft", nullable=False
            ),
            sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
            sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
            sa.Column("external_ref", sa.String(length=255), nullable=True),
            sa.Column("notes", sa.Text(), nullable=True),
            sa.Column("validated_by_user_id", sa.Integer(), nullable=True),
            sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_by_user_id", sa.Integer(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["billing_party_id"], ["billing_parties.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(
                ["booking_id"], ["booking.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(
                ["created_by_user_id"], ["user.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(
                ["validated_by_user_id"], ["user.id"], ondelete="SET NULL"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("transport_vouchers", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_transport_vouchers_billing_party_id"),
                ["billing_party_id"],
                unique=False,
            )
            batch_op.create_index(
                "ix_transport_vouchers_booking_id", ["booking_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_transport_vouchers_client_id"),
                ["client_id"],
                unique=False,
            )
            batch_op.create_index(
                "ix_transport_vouchers_company_client_created",
                ["company_id", "client_id", "created_at"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_transport_vouchers_company_id"),
                ["company_id"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_transport_vouchers_created_by_user_id"),
                ["created_by_user_id"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_transport_vouchers_validated_by_user_id"),
                ["validated_by_user_id"],
                unique=False,
            )

    if not _table_exists(conn, "transport_voucher_files"):
        op.create_table(
            "transport_voucher_files",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("voucher_id", sa.Integer(), nullable=False),
            sa.Column("file_url", sa.String(length=500), nullable=False),
            sa.Column("filename", sa.String(length=255), nullable=False),
            sa.Column("mime_type", sa.String(length=100), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["voucher_id"], ["transport_vouchers.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("transport_voucher_files", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_transport_voucher_files_voucher_id"),
                ["voucher_id"],
                unique=False,
            )

    if _index_exists(conn, "ix_assignment_created_at"):
        with op.batch_alter_table("assignment", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_assignment_created_at"))

    with op.batch_alter_table("booking", schema=None) as batch_op:
        if _index_exists(conn, "ix_booking_executing_company"):
            batch_op.drop_index(batch_op.f("ix_booking_executing_company"))
        if _index_exists(conn, "ix_booking_client_time"):
            batch_op.drop_index(batch_op.f("ix_booking_client_time"))
        if not _index_exists(conn, "ix_booking_client_time"):
            batch_op.create_index(
                "ix_booking_client_time", ["client_id", "scheduled_time"], unique=False
            )
        if not _index_exists(conn, "ix_booking_company_status_scheduled"):
            batch_op.create_index(
                "ix_booking_company_status_scheduled",
                ["company_id", "status", "scheduled_time"],
                unique=False,
            )
        if not _index_exists(conn, "ix_booking_executing_company_id"):
            batch_op.create_index(
                batch_op.f("ix_booking_executing_company_id"),
                ["executing_company_id"],
                unique=False,
            )
        if not _constraint_exists(
            conn, "booking", "booking_billing_locked_by_user_id_fkey"
        ):
            batch_op.create_foreign_key(
                None, "user", ["billing_locked_by_user_id"], ["id"], ondelete="SET NULL"
            )

    with op.batch_alter_table("driver", schema=None) as batch_op:
        batch_op.alter_column(
            "driver_photo",
            existing_type=sa.VARCHAR(length=500),
            type_=sa.String(length=50000),
            existing_nullable=True,
        )

    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        if _index_exists(conn, "ix_refresh_token_token_hash"):
            batch_op.drop_index(batch_op.f("ix_refresh_token_token_hash"))
        if not _index_exists(conn, "ix_refresh_token_token_hash"):
            batch_op.create_index(
                "ix_refresh_token_token_hash", ["token_hash"], unique=False
            )

    with op.batch_alter_table("user", schema=None) as batch_op:
        if not _index_exists(conn, "ix_user_password_expires_at"):
            batch_op.create_index(
                batch_op.f("ix_user_password_expires_at"),
                ["password_expires_at"],
                unique=False,
            )
        if not _index_exists(conn, "ix_user_push_token"):
            batch_op.create_index(
                batch_op.f("ix_user_push_token"), ["push_token"], unique=False
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe downgrade: drop tables/indexes/constraints only if they exist.
    # Ordre: dépendants d'abord (user/refresh_token/booking/assignment), puis tables.
    conn = op.get_bind()

    with op.batch_alter_table("user", schema=None) as batch_op:
        if _index_exists(conn, "ix_user_push_token"):
            batch_op.drop_index(batch_op.f("ix_user_push_token"))
        if _index_exists(conn, "ix_user_password_expires_at"):
            batch_op.drop_index(batch_op.f("ix_user_password_expires_at"))

    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        if _index_exists(conn, "ix_refresh_token_token_hash"):
            batch_op.drop_index("ix_refresh_token_token_hash")
        if not _index_exists(conn, "ix_refresh_token_token_hash"):
            batch_op.create_index(
                batch_op.f("ix_refresh_token_token_hash"), ["token_hash"], unique=True
            )

    with op.batch_alter_table("driver", schema=None) as batch_op:
        batch_op.alter_column(
            "driver_photo",
            existing_type=sa.String(length=50000),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )

    with op.batch_alter_table("booking", schema=None) as batch_op:
        fk_name = _get_fk_constraint_name(
            conn, "booking", "billing_locked_by_user_id", "user"
        )
        if fk_name:
            batch_op.drop_constraint(fk_name, type_="foreignkey")
        if _index_exists(conn, "ix_booking_executing_company_id"):
            batch_op.drop_index(batch_op.f("ix_booking_executing_company_id"))
        if _index_exists(conn, "ix_booking_company_status_scheduled"):
            batch_op.drop_index("ix_booking_company_status_scheduled")
        if _index_exists(conn, "ix_booking_client_time"):
            batch_op.drop_index("ix_booking_client_time")
        if not _index_exists(conn, "ix_booking_client_time"):
            batch_op.create_index(
                batch_op.f("ix_booking_client_time"),
                ["client_id", sa.literal_column("scheduled_time DESC")],
                unique=False,
            )
        if not _index_exists(conn, "ix_booking_executing_company"):
            batch_op.create_index(
                batch_op.f("ix_booking_executing_company"),
                ["executing_company_id"],
                unique=False,
            )

    if not _index_exists(conn, "ix_assignment_created_at"):
        with op.batch_alter_table("assignment", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_assignment_created_at"),
                [sa.literal_column("created_at DESC")],
                unique=False,
            )

    if _table_exists(conn, "transport_voucher_files"):
        with op.batch_alter_table("transport_voucher_files", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_transport_voucher_files_voucher_id"))
        op.drop_table("transport_voucher_files")

    if _table_exists(conn, "transport_vouchers"):
        with op.batch_alter_table("transport_vouchers", schema=None) as batch_op:
            batch_op.drop_index(
                batch_op.f("ix_transport_vouchers_validated_by_user_id")
            )
            batch_op.drop_index(batch_op.f("ix_transport_vouchers_created_by_user_id"))
            batch_op.drop_index(batch_op.f("ix_transport_vouchers_company_id"))
            batch_op.drop_index("ix_transport_vouchers_company_client_created")
            batch_op.drop_index(batch_op.f("ix_transport_vouchers_client_id"))
            batch_op.drop_index("ix_transport_vouchers_booking_id")
            batch_op.drop_index(batch_op.f("ix_transport_vouchers_billing_party_id"))
        op.drop_table("transport_vouchers")

    if _table_exists(conn, "device_tokens"):
        with op.batch_alter_table("device_tokens", schema=None) as batch_op:
            batch_op.drop_index("ix_device_tokens_token")
            batch_op.drop_index("ix_device_tokens_driver_id")
            batch_op.drop_index("ix_device_tokens_driver_active")
        op.drop_table("device_tokens")

    if _table_exists(conn, "company_billing_profile"):
        with op.batch_alter_table("company_billing_profile", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_company_billing_profile_uid_ide"))
            batch_op.drop_index(batch_op.f("ix_company_billing_profile_company_id"))
        op.drop_table("company_billing_profile")

    if _table_exists(conn, "billing_audit_logs"):
        with op.batch_alter_table("billing_audit_logs", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_billing_audit_logs_company_id"))
            batch_op.drop_index(batch_op.f("ix_billing_audit_logs_booking_id"))
            batch_op.drop_index(batch_op.f("ix_billing_audit_logs_actor_user_id"))
        op.drop_table("billing_audit_logs")

    if _table_exists(conn, "password_history"):
        with op.batch_alter_table("password_history", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_password_history_user_id"))
            batch_op.drop_index("ix_password_history_user_created")
            batch_op.drop_index(batch_op.f("ix_password_history_created_at"))
        op.drop_table("password_history")
    # ### end Alembic commands ###
