"""billing_parties_v1

Revision ID: 4e968efb2f32
Revises: e34565d5b10d
Create Date: 2026-01-21 10:35:22.447703

"""

from alembic import op
import sqlalchemy as sa


revision = "4e968efb2f32"
down_revision = "e34565d5b10d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "patient",
                "clinic",
                "ems",
                "hospital",
                "curatorship",
                "opad",
                "lawyer",
                "family",
                "insurance",
                "other",
                name="billing_party_type",
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("external_ref", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_parties_company_id"),
        "billing_parties",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_billing_parties_company_type",
        "billing_parties",
        ["company_id", "type"],
        unique=False,
    )
    op.create_table(
        "client_billing_parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("billing_party_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["billing_party_id"], ["billing_parties.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_billing_parties_billing_party_id"),
        "client_billing_parties",
        ["billing_party_id"],
        unique=False,
    )
    op.create_index(
        "ix_client_billing_parties_client_default",
        "client_billing_parties",
        ["client_id", "is_default"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_billing_parties_client_id"),
        "client_billing_parties",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        "ix_client_billing_parties_unique",
        "client_billing_parties",
        ["client_id", "billing_party_id"],
        unique=True,
    )
    # NOTE: Ce fichier de migration est dédié aux tables BillingParty.
    # Le changement d'index refresh_token est un bruit d'autogénération (diff metadata/DB)
    # et ne doit pas être couplé à cette migration.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_client_billing_parties_unique", table_name="client_billing_parties"
    )
    op.drop_index(
        op.f("ix_client_billing_parties_client_id"), table_name="client_billing_parties"
    )
    op.drop_index(
        "ix_client_billing_parties_client_default", table_name="client_billing_parties"
    )
    op.drop_index(
        op.f("ix_client_billing_parties_billing_party_id"),
        table_name="client_billing_parties",
    )
    op.drop_table("client_billing_parties")
    op.drop_index("ix_billing_parties_company_type", table_name="billing_parties")
    op.drop_index(op.f("ix_billing_parties_company_id"), table_name="billing_parties")
    op.drop_table("billing_parties")
    # ### end Alembic commands ###
