
"""invoice_billing_party_id_v1

Revision ID: 502ee3c14a85
Revises: 3cdf4454ec3c
Create Date: 2026-01-21 12:48:21.050250

"""
from alembic import op
import sqlalchemy as sa


revision = "502ee3c14a85"
down_revision = "3cdf4454ec3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("billing_party_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_invoices_billing_party_id"), "invoices", ["billing_party_id"], unique=False)
    op.create_foreign_key(None, "invoices", "billing_parties", ["billing_party_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_index(op.f("ix_invoices_billing_party_id"), table_name="invoices")
    op.drop_column("invoices", "billing_party_id")
    # ### end Alembic commands ###

