
"""email signature form fields

Revision ID: 5ad79a6e8d27
Revises: 1bbbda3dd455
Create Date: 2026-01-27 03:10:35.637860

"""
from alembic import op
import sqlalchemy as sa


revision = "5ad79a6e8d27"
down_revision = '1bbbda3dd455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.create_index('ix_refresh_token_token_hash', ['token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_token_token_hash')
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###

