"""Initialisation de la base de données

Revision ID: 5c88abe5821e
Revises: 
Create Date: 2025-08-04 20:20:33.457015

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import models


# revision identifiers, used by Alembic.
revision = '5c88abe5821e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('homme', 'femme', 'autre', name='genderenum'), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'client', 'driver', 'company', name='user_role'), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_token')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_public_id', ['public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_area', sa.String(length=200), nullable=True),
    sa.Column('max_daily_bookings', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('dispatch_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_company_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_user_id'), ['user_id'], unique=False)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.Enum('SELF_SERVICE', 'PRIVATE', 'CORPORATE', name='client_type'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('billing_address', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_user_id'), ['user_id'], unique=False)

    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_assigned', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('license_plate', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('driver_type', sa.Enum('REGULAR', 'EMERGENCY', name='drivertype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_position_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_photo', sa.Text(), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_push_token'), ['push_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_user_id'), ['user_id'], unique=True)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.CheckConstraint("sender_role IN ('driver', 'company')", name='check_sender_role_valid'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('pickup_location', sa.String(length=200), nullable=False),
    sa.Column('dropoff_location', sa.String(length=200), nullable=False),
    sa.Column('booking_type', sa.String(length=200), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'ASSIGNED', 'EN_ROUTE', 'IN_PROGRESS', 'COMPLETED', 'RETURN_COMPLETED', 'CANCELED', name='bookingstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rejected_by', models.JSONEncodedList(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('is_round_trip', sa.Boolean(), nullable=True),
    sa.Column('is_return', sa.Boolean(), nullable=True),
    sa.Column('boarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_booking_id', sa.Integer(), nullable=True),
    sa.Column('medical_facility', sa.String(length=200), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('hospital_service', sa.String(length=100), nullable=True),
    sa.Column('notes_medical', sa.Text(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lon', sa.Float(), nullable=True),
    sa.Column('dropoff_lat', sa.Float(), nullable=True),
    sa.Column('dropoff_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_booking_id'], ['booking.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_status'), ['status'], unique=False)

    op.create_table('driver_vacations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('vacation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_working_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('earliest_start', sa.Integer(), nullable=True),
    sa.Column('latest_start', sa.Integer(), nullable=True),
    sa.Column('total_working_minutes', sa.Integer(), nullable=True),
    sa.Column('break_duration', sa.Integer(), nullable=True),
    sa.Column('break_earliest', sa.Integer(), nullable=True),
    sa.Column('break_latest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_working_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_working_config_driver_id'), ['driver_id'], unique=True)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'CANCELED', name='invoice_status'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='fk_invoice_booking', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_invoice_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_invoice_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_user_id'), ['user_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_reference'))
        batch_op.drop_index(batch_op.f('ix_invoice_company_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_booking_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('driver_working_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_working_config_driver_id'))

    op.drop_table('driver_working_config')
    op.drop_table('driver_vacations')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_status'))
        batch_op.drop_index(batch_op.f('ix_booking_driver_id'))
        batch_op.drop_index(batch_op.f('ix_booking_company_id'))
        batch_op.drop_index(batch_op.f('ix_booking_client_id'))

    op.drop_table('booking')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    op.drop_table('message')
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_user_id'))
        batch_op.drop_index(batch_op.f('ix_driver_push_token'))
        batch_op.drop_index(batch_op.f('ix_driver_company_id'))

    op.drop_table('driver')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_company_id'))

    op.drop_table('client')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_user_id'))

    op.drop_table('company')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_public_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index('idx_public_id')

    op.drop_table('user')
    # ### end Alembic commands ###
