"""Update models.py

Revision ID: 6af879898b0f
Revises: 623409ab335b
Create Date: 2025-10-08 13:22:08.337476

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types import StringEncryptedType

# revision identifiers, used by Alembic.
revision = "6af879898b0f"
down_revision = "623409ab335b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("driver", schema=None) as batch_op:
        batch_op.alter_column("license_plate",
               existing_type=sa.TEXT(),
               type_=StringEncryptedType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("driver", schema=None) as batch_op:
        batch_op.alter_column("license_plate",
               existing_type=sa.TEXT(),
               type_=StringEncryptedType(),
               existing_nullable=True)

    # ### end Alembic commands ###
