"""add timezone to driver_shift

Revision ID: 6d50ede67619
Revises: a452a931f0b7
Create Date: 2025-10-09 12:25:47.658343

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6d50ede67619'
down_revision = 'a452a931f0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_planning_settings',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('driver_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('mornings_pref', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('evenings_pref', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('forbidden_windows', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('weekend_rotation_weight', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_preference_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_preference_driver_id'), ['driver_id'], unique=False)

    with op.batch_alter_table('driver_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='Europe/Zurich', nullable=False))
        batch_op.add_column(sa.Column('site', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('zone', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('client_ref', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pay_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes_internal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes_employee', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('compliance_flags', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.create_index(batch_op.f('ix_driver_shift_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['updated_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_shift', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_driver_shift_vehicle_id'))
        batch_op.drop_column('compliance_flags')
        batch_op.drop_column('version')
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('notes_employee')
        batch_op.drop_column('notes_internal')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('pay_code')
        batch_op.drop_column('client_ref')
        batch_op.drop_column('zone')
        batch_op.drop_column('site')
        batch_op.drop_column('timezone')

    with op.batch_alter_table('driver_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_preference_driver_id'))
        batch_op.drop_index(batch_op.f('ix_driver_preference_company_id'))

    op.drop_table('driver_preference')
    op.drop_table('company_planning_settings')
    # ### end Alembic commands ###
