"""add_analytics_tables_for_dispatch_metrics

Revision ID: 715e89e538c3
Revises: e252718b5271
Create Date: 2025-10-14 02:07:46.209700

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "715e89e538c3"
down_revision = "e252718b5271"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_bookings", sa.Integer(), nullable=False),
        sa.Column("on_time_rate", sa.Float(), nullable=False),
        sa.Column("avg_delay", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("bookings_trend", sa.Float(), nullable=False),
        sa.Column("delay_trend", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "date", name="uq_daily_stats_company_date"),
    )
    with op.batch_alter_table("daily_stats", schema=None) as batch_op:
        batch_op.create_index(
            "ix_daily_stats_company_date", ["company_id", "date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_daily_stats_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_daily_stats_date"), ["date"], unique=False)

    op.create_table(
        "dispatch_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("dispatch_run_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("total_bookings", sa.Integer(), nullable=False),
        sa.Column("on_time_bookings", sa.Integer(), nullable=False),
        sa.Column("delayed_bookings", sa.Integer(), nullable=False),
        sa.Column("cancelled_bookings", sa.Integer(), nullable=False),
        sa.Column("average_delay_minutes", sa.Float(), nullable=False),
        sa.Column("max_delay_minutes", sa.Integer(), nullable=False),
        sa.Column("total_delay_minutes", sa.Integer(), nullable=False),
        sa.Column("total_drivers", sa.Integer(), nullable=False),
        sa.Column("active_drivers", sa.Integer(), nullable=False),
        sa.Column("avg_bookings_per_driver", sa.Float(), nullable=False),
        sa.Column("total_distance_km", sa.Float(), nullable=False),
        sa.Column("avg_distance_per_booking", sa.Float(), nullable=False),
        sa.Column("suggestions_generated", sa.Integer(), nullable=False),
        sa.Column("suggestions_applied", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["dispatch_run_id"], ["dispatch_run.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dispatch_metrics", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dispatch_metrics_company_date", ["company_id", "date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dispatch_metrics_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dispatch_metrics_date"), ["date"], unique=False
        )
        batch_op.create_index(
            "ix_dispatch_metrics_dispatch_run", ["dispatch_run_id"], unique=False
        )

    booking_columns = {col["name"] for col in inspector.get_columns("booking")}

    if "time_confirmed" not in booking_columns:
        with op.batch_alter_table("booking", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "time_confirmed",
                    sa.Boolean(),
                    server_default=sa.text("true"),
                    nullable=False,
                )
            )
    else:
        with op.batch_alter_table("booking", schema=None) as batch_op:
            batch_op.alter_column(
                "time_confirmed",
                existing_type=sa.BOOLEAN(),
                nullable=False,
                existing_server_default=sa.text("true"),
            )

    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column(
            "preferential_rate",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            comment=None,
            existing_comment="Tarif préférentiel en CHF (ex: 45, 50, 55, 60, 70, 80, 110). NULL = tarif standard",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column(
            "preferential_rate",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            comment="Tarif préférentiel en CHF (ex: 45, 50, 55, 60, 70, 80, 110). NULL = tarif standard",
            existing_nullable=True,
        )

    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.alter_column(
            "time_confirmed",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),
        )

    with op.batch_alter_table("dispatch_metrics", schema=None) as batch_op:
        batch_op.drop_index("ix_dispatch_metrics_dispatch_run")
        batch_op.drop_index(batch_op.f("ix_dispatch_metrics_date"))
        batch_op.drop_index(batch_op.f("ix_dispatch_metrics_company_id"))
        batch_op.drop_index("ix_dispatch_metrics_company_date")

    op.drop_table("dispatch_metrics")
    with op.batch_alter_table("daily_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_stats_date"))
        batch_op.drop_index(batch_op.f("ix_daily_stats_company_id"))
        batch_op.drop_index("ix_daily_stats_company_date")

    op.drop_table("daily_stats")
    # ### end Alembic commands ###
