
"""add_refresh_token_table

Revision ID: 930de29a8cae
Revises: d73f133dd06f
Create Date: 2025-12-03 17:54:37.684840

"""
from alembic import op
import sqlalchemy as sa


revision = "930de29a8cae"
down_revision = 'd73f133dd06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_refresh_token_user_active', ['user_id', 'is_revoked'], unique=False)
        batch_op.create_index('ix_refresh_token_user_id', ['user_id'], unique=False)

    op.drop_table('backup_test_validation')
    with op.batch_alter_table('app_version_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_app_version_config_platform'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_app_version_config_platform'))
        batch_op.create_index(batch_op.f('ix_app_version_config_platform'), ['platform'], unique=True)

    with op.batch_alter_table('trip_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_tracking_assignment_id'), ['assignment_id'], unique=False)

    with op.batch_alter_table('trip_tracking_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_tracking_archive_assignment_id'), ['assignment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_tracking_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_tracking_archive_assignment_id'))

    with op.batch_alter_table('trip_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_tracking_assignment_id'))

    with op.batch_alter_table('app_version_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_version_config_platform'))
        batch_op.create_index(batch_op.f('ix_app_version_config_platform'), ['platform'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_app_version_config_platform'), ['platform'], postgresql_nulls_not_distinct=False)

    op.create_table('backup_test_validation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backup_test_validation_pkey'))
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_token_user_id')
        batch_op.drop_index('ix_refresh_token_user_active')
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_expires_at'))

    op.drop_table('refresh_token')
    # ### end Alembic commands ###

