"""s3_add_password_history_and_expiration

Revision ID: 9fbfec587490
Revises: 2100d6d88008
Create Date: 2025-12-09 01:14:02.860312

"""

from alembic import op
import sqlalchemy as sa


revision = "9fbfec587490"
down_revision = "2100d6d88008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_password_history_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_password_history_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assignment_created_at"))

    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_booking_client_time"))
        batch_op.create_index(
            "ix_booking_client_time", ["client_id", "scheduled_time"], unique=False
        )
        batch_op.create_index(
            "ix_booking_company_status_scheduled",
            ["company_id", "status", "scheduled_time"],
            unique=False,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_expires_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_password_expires_at"),
            ["password_expires_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_password_expires_at"))
        batch_op.drop_column("password_expires_at")

    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_index("ix_booking_company_status_scheduled")
        batch_op.drop_index("ix_booking_client_time")
        batch_op.create_index(
            batch_op.f("ix_booking_client_time"),
            ["client_id", sa.literal_column("scheduled_time DESC")],
            unique=False,
        )

    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assignment_created_at"),
            [sa.literal_column("created_at DESC")],
            unique=False,
        )

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_history_user_id"))
        batch_op.drop_index("ix_password_history_user_created")
        batch_op.drop_index(batch_op.f("ix_password_history_created_at"))

    op.drop_table("password_history")
    # ### end Alembic commands ###
