
"""add client_stays and clinic_billing_party_mappings

Revision ID: a31b260dd7be
Revises: 502ee3c14a85
Create Date: 2026-01-21 16:07:31.423286

"""
from alembic import op
import sqlalchemy as sa


revision = "a31b260dd7be"
down_revision = "502ee3c14a85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_stays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
        ),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_stays_client_id"),
        "client_stays",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        "ix_client_stays_client_start_date",
        "client_stays",
        ["client_id", "start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_stays_company_id"),
        "client_stays",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_client_stays_company_start_date",
        "client_stays",
        ["company_id", "start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_stays_created_by_user_id"),
        "client_stays",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_table(
        "clinic_billing_party_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("clinic_company_id", sa.Integer(), nullable=False),
        sa.Column("billing_party_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["billing_party_id"], ["billing_parties.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["clinic_company_id"], ["company.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "clinic_company_id",
            name="uq_clinic_billing_party_mapping_company_clinic",
        ),
    )
    op.create_index(
        op.f("ix_clinic_billing_party_mappings_billing_party_id"),
        "clinic_billing_party_mappings",
        ["billing_party_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinic_billing_party_mappings_clinic_company_id"),
        "clinic_billing_party_mappings",
        ["clinic_company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinic_billing_party_mappings_company_id"),
        "clinic_billing_party_mappings",
        ["company_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_clinic_billing_party_mappings_company_id"),
        table_name="clinic_billing_party_mappings",
    )
    op.drop_index(
        op.f("ix_clinic_billing_party_mappings_clinic_company_id"),
        table_name="clinic_billing_party_mappings",
    )
    op.drop_index(
        op.f("ix_clinic_billing_party_mappings_billing_party_id"),
        table_name="clinic_billing_party_mappings",
    )
    op.drop_table("clinic_billing_party_mappings")
    op.drop_index(
        op.f("ix_client_stays_created_by_user_id"),
        table_name="client_stays",
    )
    op.drop_index(
        "ix_client_stays_company_start_date",
        table_name="client_stays",
    )
    op.drop_index(op.f("ix_client_stays_company_id"), table_name="client_stays")
    op.drop_index(
        "ix_client_stays_client_start_date",
        table_name="client_stays",
    )
    op.drop_index(op.f("ix_client_stays_client_id"), table_name="client_stays")
    op.drop_table("client_stays")
    # ### end Alembic commands ###

