"""medical tables

Revision ID: af64d3ec937a
Revises: f0205e526864
Create Date: 2025-09-07 18:29:48.815406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af64d3ec937a'
down_revision = 'f0205e526864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_establishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('aliases', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name='chk_med_estab_lat'),
    sa.CheckConstraint('lon BETWEEN -180 AND 180', name='chk_med_estab_lon'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', name='uq_med_estab_address'),
    sa.UniqueConstraint('name', name='uq_med_estab_name')
    )
    op.create_table('medical_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('building', sa.String(length=120), nullable=True),
    sa.Column('floor', sa.String(length=60), nullable=True),
    sa.Column('site_note', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lat IS NULL OR (lat BETWEEN -90 AND 90)', name='chk_med_service_lat'),
    sa.CheckConstraint('lon IS NULL OR (lon BETWEEN -180 AND 180)', name='chk_med_service_lon'),
    sa.ForeignKeyConstraint(['establishment_id'], ['medical_establishment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establishment_id', 'name', name='uq_med_service_per_estab')
    )
    with op.batch_alter_table('medical_service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_service_establishment_id'), ['establishment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_service_establishment_id'))

    op.drop_table('medical_service')
    op.drop_table('medical_establishment')
    # ### end Alembic commands ###
