"""add company logo_url

Revision ID: b0b4bccdd38a
Revises: b6e2a5f19332
Create Date: 2025-08-30 20:00:48.535964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b4bccdd38a'
down_revision = 'b6e2a5f19332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_booking')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('billed_to_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('default_billed_to_type',
               existing_type=sa.VARCHAR(length=50),
               server_default='patient',
               existing_nullable=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('is_partner',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('is_partner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('default_billed_to_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('billed_to_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('_alembic_tmp_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('pickup_location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('dropoff_location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('booking_type', sa.VARCHAR(length=200), nullable=True),
    sa.Column('scheduled_time', sa.DATETIME(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('rejected_by', sa.TEXT(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('distance_meters', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.Column('is_round_trip', sa.BOOLEAN(), nullable=True),
    sa.Column('is_return', sa.BOOLEAN(), nullable=True),
    sa.Column('boarded_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('parent_booking_id', sa.INTEGER(), nullable=True),
    sa.Column('medical_facility', sa.VARCHAR(length=200), nullable=True),
    sa.Column('doctor_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('hospital_service', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes_medical', sa.TEXT(), nullable=True),
    sa.Column('is_urgent', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('pickup_lat', sa.FLOAT(), nullable=True),
    sa.Column('pickup_lon', sa.FLOAT(), nullable=True),
    sa.Column('dropoff_lat', sa.FLOAT(), nullable=True),
    sa.Column('dropoff_lon', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('billed_to_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('billed_to_company_id', sa.INTEGER(), nullable=True),
    sa.Column('billed_to_contact', sa.VARCHAR(length=120), nullable=True),
    sa.ForeignKeyConstraint(['billed_to_company_id'], ['company.id'], name='fk_booking_billed_company', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_booking_id'], ['booking.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
