"""driver HR fields + timezone normalize in planning_service

Revision ID: b15c01673cc4
Revises: 6d50ede67619
Create Date: 2025-10-09 12:38:55.551149

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b15c01673cc4'
down_revision = '6d50ede67619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_type', sa.String(length=20), server_default='CDI', nullable=False))
        batch_op.add_column(sa.Column('weekly_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employment_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('employment_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('license_categories', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('license_valid_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('trainings', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('medical_valid_until', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('medical_valid_until')
        batch_op.drop_column('trainings')
        batch_op.drop_column('license_valid_until')
        batch_op.drop_column('license_categories')
        batch_op.drop_column('employment_end_date')
        batch_op.drop_column('employment_start_date')
        batch_op.drop_column('hourly_rate_cents')
        batch_op.drop_column('weekly_hours')
        batch_op.drop_column('contract_type')

    # ### end Alembic commands ###
