
"""add_preferential_rate_to_company

Revision ID: b59281cc564a
Revises: c9d8e7f6a5b4
Create Date: 2026-01-23 13:54:18.784885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "b59281cc564a"
down_revision = "c9d8e7f6a5b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Cette migration ne contient que l'ajout de preferential_rate à company
    # Les autres changements détectés existent déjà en base

    # Ajouter uniquement preferential_rate à company
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "preferential_rate",
                sa.Numeric(precision=10, scale=2),
                nullable=True,
                comment="Tarif préférentiel en CHF pour les cliniques",
            )
        )

    # Les autres opérations suivantes sont commentées car elles existent déjà
    """
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_password_history_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_history_user_id'), ['user_id'], unique=False)

    op.create_table('billing_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_audit_logs_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_audit_logs_company_id'), ['company_id'], unique=False)

    op.create_table('company_billing_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False, comment="Nom légal de l'entreprise pour factures"),
    sa.Column('brand_name', sa.String(length=200), nullable=True, comment='Nom commercial (si différent du nom légal)'),
    sa.Column('uid_ide', sa.String(length=20), nullable=False, comment='Numéro IDE/UID suisse (format: CHE-XXX.XXX.XXX)'),
    sa.Column('street_name', sa.String(length=70), nullable=False, comment='Nom de rue (sans numéro)'),
    sa.Column('building_number', sa.String(length=16), nullable=False, comment='Numéro de bâtiment (peut contenir lettres: 12A)'),
    sa.Column('postal_code', sa.String(length=16), nullable=False, comment='Code postal (4 chiffres pour Suisse)'),
    sa.Column('city', sa.String(length=35), nullable=False, comment='Ville'),
    sa.Column('country_code', sa.String(length=2), nullable=False, comment='Code pays ISO 3166-1 alpha-2'),
    sa.Column('billing_email', sa.String(length=100), nullable=False, comment='Email pour envoi factures'),
    sa.Column('billing_phone', sa.String(length=20), nullable=False, comment='Téléphone facturation (format international recommandé)'),
    sa.Column('vat_registered', sa.Boolean(), nullable=False, comment='Entreprise assujettie à la TVA'),
    sa.Column('vat_number', sa.String(length=50), nullable=True, comment='Numéro TVA (si assujetti)'),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Taux TVA par défaut (ex: 7.7 pour 7.7%)'),
    sa.Column('iban', sa.String(length=200), nullable=False, comment='IBAN chiffré (format CHxx xxxx xxxx xxxx xxxx x)'),
    sa.Column('qr_iban', sa.String(length=200), nullable=True, comment='QR-IBAN chiffré (uniquement si références QRR)'),
    sa.Column('payment_reference_mode', sa.String(length=10), nullable=False, comment='Mode référence paiement: NONE, SCOR (ISO 11649), QRR (ESR)'),
    sa.Column('creditor_reference_base', sa.String(length=20), nullable=True, comment='Base pour générer références QRR (si mode=QRR)'),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False, comment='Délai de paiement en jours'),
    sa.Column('overdue_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='Frais de retard (CHF)'),
    sa.Column('legal_footer', sa.Text(), nullable=True, comment='Texte légal pied de page facture'),
    sa.Column('is_address_validated', sa.Boolean(), nullable=False, comment='Adresse validée (structure + existence)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_billing_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_billing_profile_company_id'), ['company_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_billing_profile_uid_ide'), ['uid_ide'], unique=False)

    op.create_table('partnerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_company_id', sa.Integer(), nullable=False),
    sa.Column('partner_company_id', sa.Integer(), nullable=False),
    sa.Column('default_transfer_model', sa.Enum('SUBCONTRACT', 'ASSIGN_TO_PARTNER', 'MARKETPLACE', name='transfer_model'), nullable=False),
    sa.Column('default_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('default_partner_tariff_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('auto_accept_rules', sa.Boolean(), nullable=False),
    sa.Column('auto_invoice', sa.Boolean(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='partnership_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_company_id', 'partner_company_id', name='unique_partnership')
    )
    with op.batch_alter_table('partnerships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partnerships_owner_company_id'), ['owner_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnerships_partner_company_id'), ['partner_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnerships_status'), ['status'], unique=False)

    op.create_table('booking_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('partnership_id', sa.Integer(), nullable=False),
    sa.Column('transfer_model', sa.Enum('SUBCONTRACT', 'ASSIGN_TO_PARTNER', 'MARKETPLACE', name='transfer_model'), nullable=False),
    sa.Column('owner_company_id', sa.Integer(), nullable=False),
    sa.Column('executing_company_id', sa.Integer(), nullable=False),
    sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('partner_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_included', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='transfer_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executing_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['owner_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnerships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_transfers_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_transfers_executing_company_id'), ['executing_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_transfers_owner_company_id'), ['owner_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_transfers_partnership_id'), ['partnership_id'], unique=False)

    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_device_tokens_driver_active', ['driver_id', 'is_active'], unique=False)
        batch_op.create_index('ix_device_tokens_driver_id', ['driver_id'], unique=False)
        batch_op.create_index('ix_device_tokens_token', ['token'], unique=False)

    op.create_table('partner_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partnership_id', sa.Integer(), nullable=False),
    sa.Column('executing_company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credit_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['executing_company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnerships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('partner_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_invoices_executing_company_id'), ['executing_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_invoices_partnership_id'), ['partnership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_invoices_period_month'), ['period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_invoices_period_year'), ['period_year'], unique=False)

    op.create_table('transport_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('billing_party_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), server_default='clinic', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_party_id'], ['billing_parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_vouchers', schema=None) as batch_op:
        batch_op.create_index('ix_transport_vouchers_billing_party_id', ['billing_party_id'], unique=False)
        batch_op.create_index('ix_transport_vouchers_booking_id', ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_vouchers_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_transport_vouchers_company_client_created', ['company_id', 'client_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_vouchers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_vouchers_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_vouchers_validated_by_user_id'), ['validated_by_user_id'], unique=False)

    op.create_table('partner_invoice_transfers',
    sa.Column('partner_invoice_id', sa.Integer(), nullable=False),
    sa.Column('booking_transfer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_transfer_id'], ['booking_transfers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_invoice_id'], ['partner_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_invoice_id', 'booking_transfer_id')
    )
    op.create_table('transport_voucher_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['transport_vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_voucher_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_voucher_files_voucher_id'), ['voucher_id'], unique=False)

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_created_at'))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executing_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('booking_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_review_status', sa.Enum('draft', 'needs_review', 'ready', 'locked', name='billing_review_status'), server_default='draft', nullable=False))
        batch_op.add_column(sa.Column('billing_locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('billing_locked_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_override_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('billing_party_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_source', sa.Enum('default_client', 'transport_voucher', 'client_stay', 'manual_override', 'import', 'system_rule', name='billing_source'), nullable=True))
        batch_op.add_column(sa.Column('billing_source_ref', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_booking_client_time'))
        batch_op.create_index('ix_booking_client_time', ['client_id', 'scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_billing_locked_by_user_id'), ['billing_locked_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_billing_party_id'), ['billing_party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_booking_group_id'), ['booking_group_id'], unique=False)
        batch_op.create_index('ix_booking_company_status_scheduled', ['company_id', 'status', 'scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_executing_company_id'), ['executing_company_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['billing_locked_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'company', ['executing_company_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'billing_parties', ['billing_party_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'booking', ['booking_group_id'], ['id'], ondelete='SET NULL')

    """


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.drop_column("preferential_rate")

    # Les autres opérations suivantes sont commentées car elles existent déjà
    """
    with op.batch_alter_table('company_billing_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_server', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smtp_use_tls', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('smtp_use_ssl', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('smtp_username', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('smtp_password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('smtp_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('from_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('domain_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('domain_dns_records', sa.JSON(), nullable=True))

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.alter_column('driver_photo',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=50000),
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_party_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_strategy', sa.Enum('s1_patient', 's2_clinic_monthly', name='invoice_billing_strategy'), server_default='s1_patient', nullable=False))
        batch_op.add_column(sa.Column('billed_to_company_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_billed_to_company_id'), ['billed_to_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_billing_party_id'), ['billing_party_id'], unique=False)
        batch_op.create_foreign_key(None, 'company', ['billed_to_company_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'billing_parties', ['billing_party_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_password_expires_at'), ['password_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_push_token'), ['push_token'], unique=False)

    """
    # ### end Alembic commands ###

