"""add_third_party_billing_support

Revision ID: c8d4e92f1a3b
Revises: b15c01673cc4
Create Date: 2025-10-10 14:30:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8d4e92f1a3b"
down_revision = "b15c01673cc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Ajouter le champ is_institution à la table client
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_institution", sa.Boolean(), nullable=False, server_default="false"))
        batch_op.add_column(sa.Column("institution_name", sa.String(length=0.200), nullable=True))

    # Ajouter le champ bill_to_client_id à la table invoices
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bill_to_client_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_invoices_bill_to_client", "client", ["bill_to_client_id"], ["id"])
        batch_op.create_index("ix_invoices_bill_to_client_id", ["bill_to_client_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Retirer les modifications de la table invoices
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index("ix_invoices_bill_to_client_id")
        batch_op.drop_constraint("fk_invoices_bill_to_client", type_="foreignkey")
        batch_op.drop_column("bill_to_client_id")

    # Retirer les modifications de la table client
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.drop_column("institution_name")
        batch_op.drop_column("is_institution")

    # ### end Alembic commands ###

