"""client_habitual_mobility

Revision ID: d98f32ddd475
Revises: b41d4242fe1a
Create Date: 2026-09-28 16:05:04.462246

"""

from alembic import op
import sqlalchemy as sa


revision = "d98f32ddd475"
down_revision = "b41d4242fe1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "habitual_wheelchair_client_has",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "habitual_wheelchair_need",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "habitual_needs_assistance",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "habitual_needs_assistance")
    op.drop_column("client", "habitual_wheelchair_need")
    op.drop_column("client", "habitual_wheelchair_client_has")
    # ### end Alembic commands ###
