"""add_invoice_line_id_to_booking

Revision ID: d9f3a8b2c4e5
Revises: c8d4e92f1a3b
Create Date: 2025-10-10 15:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9f3a8b2c4e5"
down_revision = "c8d4e92f1a3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Ajouter le champ invoice_line_id à la table booking
    # Cela permet de marquer une réservation comme déjà facturée
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.add_column(sa.Column("invoice_line_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_booking_invoice_line", "invoice_lines", ["invoice_line_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_index("ix_booking_invoice_line_id", ["invoice_line_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_index("ix_booking_invoice_line_id")
        batch_op.drop_constraint("fk_booking_invoice_line", type_="foreignkey")
        batch_op.drop_column("invoice_line_id")

    # ### end Alembic commands ###
