"""add favorite_place table

Revision ID: da49cc0736e1
Revises: b0b4bccdd38a
Create Date: 2025-09-04 19:57:43.717431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da49cc0736e1'
down_revision = 'b0b4bccdd38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite_place', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_place_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_place', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_place_company_id'))

    op.drop_table('favorite_place')
    # ### end Alembic commands ###
