"""add_company_push_token

Revision ID: e34565d5b10d
Revises: 81ffc072d63d
Create Date: 2026-01-20 16:18:59.472777

"""

from alembic import op
import sqlalchemy as sa


revision = "e34565d5b10d"
down_revision = "81ffc072d63d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("push_token", sa.String(length=255), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_push_token"), ["push_token"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_push_token"))
        batch_op.drop_column("push_token")

    # ### end Alembic commands ###
