"""empty message

Revision ID: f0205e526864
Revises: da49cc0736e1
Create Date: 2025-09-04 20:50:52.211124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0205e526864'
down_revision = 'da49cc0736e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_index('ix_fav_company_coords', ['company_id', 'lat', 'lon'], unique=False)
        batch_op.create_index('ix_fav_company_label', ['company_id', 'label'], unique=False)
        batch_op.create_unique_constraint('uq_fav_company_address', ['company_id', 'address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_place', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fav_company_address', type_='unique')
        batch_op.drop_index('ix_fav_company_label')
        batch_op.drop_index('ix_fav_company_coords')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
