
"""add_booking_pickup_dropoff_access_notes

Revision ID: f2b0c6600828
Revises: add_user_push_privacy
Create Date: 2026-01-28 21:16:42.388211

"""
from alembic import op
import sqlalchemy as sa


revision = "f2b0c6600828"
down_revision = 'add_user_push_privacy'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_access_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_access_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('dropoff_access_notes')
        batch_op.drop_column('pickup_access_notes')

    # ### end Alembic commands ###

